export default {
	"HELLO": "Hello G.",
	"SIMS":"SIMS",
	"DEVICES":"DEVICES",
	"BILLING":"BILLING",
	"AUTOMATION":"AUTOMATION",
	"SIGNOUT":"SIGNOUT",
	"REPORTS":"REPORTS",
	"ADMINISTRATION":"ADMINISTRATION",
	"SIMNUMBER":"SIM NUMBER",
	"DATARATEPLAN":"DATA RATE PLAN",
	"ACTIVESESSION":"ACTIVE SESSION",
	"IPADDRESS":"IP ADDRESS",
	"NETWORK":"NETWORK",
	"COUNTRY":"COUNTRY",
	"STATUS":"STATUS",
  "PRODUCT_TITLE":"PRODUCT NAME",
  "SECTION_TITLE":"Sim management"
}
